// Export the rules in main.ts as a KE-complex_modifications ruleset.
//
// Usage:
//   bun run scripts/export-ke.ts [output root] [--install]
//
// The output root defaults to dist/. Pass the path to a clone of
// pqrs-org/KE-complex_modifications to write the files in place.
// --install also copies the ruleset to Karabiner-Elements' assets directory
// so it can be imported from Settings > Complex Modifications > Add rule.
import { spawnSync } from "child_process";
import { copyFileSync, mkdirSync, writeFileSync } from "fs";
import { homedir } from "os";
import { dirname, join } from "path";
import { exit } from "process";
import { fileURLToPath } from "url";

const maintainer = "cafe6a6e";
const baseName = `personal_${maintainer}`;
const title = `Personal rules (@${maintainer})`;

const repoRoot = fileURLToPath(new URL("..", import.meta.url));
const args = process.argv.slice(2);
const install = args.includes("--install");
const outRoot = args.find((a) => !a.startsWith("--")) ?? join(repoRoot, "dist");

const dryRun = spawnSync("bun", ["run", "main.ts", "--dry-run"], {
  cwd: repoRoot,
  encoding: "utf8",
});
if (dryRun.status !== 0) {
  console.error(dryRun.stderr);
  exit(1);
}
const rules = JSON.parse(dryRun.stdout).profiles[0].complex_modifications.rules;
if (!Array.isArray(rules) || rules.length === 0) {
  console.error("No rules generated by main.ts.");
  exit(1);
}

const jsonPath = join(outRoot, "public/json", `${baseName}.json`);
const htmlPath = join(
  outRoot,
  "public/extra_descriptions",
  `${baseName}.json.html`,
);
mkdirSync(dirname(jsonPath), { recursive: true });
mkdirSync(dirname(htmlPath), { recursive: true });
const ruleset = { title, maintainers: [maintainer], rules };
writeFileSync(jsonPath, JSON.stringify(ruleset, null, 2) + "\n");
copyFileSync(join(repoRoot, "ke/extra_description.html"), htmlPath);
console.log(`✓ ${jsonPath} (${rules.length} rules)`);
console.log(`✓ ${htmlPath}`);

if (install) {
  const assetsDir = join(
    homedir(),
    ".config/karabiner/assets/complex_modifications",
  );
  mkdirSync(assetsDir, { recursive: true });
  copyFileSync(jsonPath, join(assetsDir, `${baseName}.json`));
  console.log(`✓ Installed to ${assetsDir}`);
}

console.log(`
Add this entry to the "personal-settings" files in public/groups.json:
{
  "path": "json/${baseName}.json",
  "extra_description_path": "extra_descriptions/${baseName}.json.html"
}`);
